[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib/forge-std']
test = 'test'
cache_path = 'cache_forge'
solc_version = '0.8.28'
optimizer_runs = 10_000
evm_version = 'cancun'
bytecode_hash = "none"
cbor_metadata = false
auto_detect_remappings = false